# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sverchok CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      blender_version: "3.6.16"
      major_blender_version: "3.6"
      python_version: "3.10"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{env.python_version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.python_version}}
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ./installation
        key: blender-${{ env.blender_version }}-${{ hashFiles('.github/workflows/test-sverchok.yml') }}
    - name: Install Blender
      run: |
        # echo "starting run"
        BLENDER_VERSION=${{env.blender_version}}
        MAJOR_BLENDER_VERSION=${{env.major_blender_version}}
        BLENDER_URL=https://mirrors.de.sahilister.net/blender/release/Blender3.6/blender-3.6.16-linux-x64.tar.xz
        SVERCHOK_DIR=scripts/addons/sverchok
        BLENDER_TAR=$(basename $BLENDER_URL)
        BLENDER_DIR=$(basename $BLENDER_URL .tar.xz)
        RELEASE=blender3616_LTS

        if [ ! -f installation/blender/blender ]
        then
            mkdir -p installation
            cd installation

            # not verbose, but not quiet.
            wget -nv $BLENDER_URL

            # unpack this tar to a known name
            mkdir $RELEASE
            tar xf $BLENDER_TAR -C $RELEASE --strip-components 1

            rm $BLENDER_TAR
            mv $RELEASE blender

            pushd blender/
            PYTHON=${MAJOR_BLENDER_VERSION}/python/bin/python${{env.python_version}}
            $PYTHON -m ensurepip
            $PYTHON -m pip install --upgrade pip setuptools wheel
            $PYTHON -m pip install --upgrade scipy geomdl scikit-image
            popd

            cd ..
        fi

        #mkdir -p ${PWD}/installation/blender/${BLENDER_VERSION}/${SVERCHOK_DIR}
        ln -s ${PWD} ${PWD}/installation/blender/${MAJOR_BLENDER_VERSION}/${SVERCHOK_DIR}
        mkdir -p ~/.config/blender/${MAJOR_BLENDER_VERSION}/config/
        ln -s ${PWD}/tests/references/userpref.blend ~/.config/blender/${MAJOR_BLENDER_VERSION}/config/
        
    - name: Test it
      run: |
        bash ./run_tests.sh
      env:
        BLENDER: |
          ./installation/blender/blender-softwaregl

    - name: Save logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: log_files
        retention-days: 5
        path: |
          ./tests/sverchok_tests.log
          ./tests/log_files/
